# Generated by Django 5.0.4 on 2024-04-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIASSISTANT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_answer',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question_answer',
            old_name='Question',
            new_name='question',
        ),
    ]
